# Resolve o erro de tabela PRODUTO não encontrada
spring.jpa.defer-datasource-initialization=true

# Configurações do Banco de Dados H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra os comandos SQL no seu terminal (ajuda a ver o Hibernate trabalhando)
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:nrbrownies